'use client';

import { create } from 'zustand';

// ─── Memory Engine Types ───

export type MemoryType =
  | 'long-term'
  | 'short-term'
  | 'episodic'
  | 'semantic'
  | 'context'
  | 'project'
  | 'user'
  | 'team'
  | 'conversation';

export type MemorySource =
  | 'chat'
  | 'file'
  | 'meeting'
  | 'email'
  | 'website'
  | 'pdf'
  | 'document'
  | 'manual';

export type RelationType =
  | 'relates_to'
  | 'depends_on'
  | 'causes'
  | 'part_of'
  | 'contradicts'
  | 'supports'
  | 'derived_from'
  | 'references';

export type ExtractedType =
  | 'fact'
  | 'task'
  | 'preference'
  | 'goal'
  | 'contact'
  | 'company'
  | 'requirement'
  | 'decision';

export type ExtractionStatus = 'pending' | 'confirmed' | 'rejected';

export type TimelineEventType =
  | 'created'
  | 'updated'
  | 'referenced'
  | 'shared'
  | 'extracted'
  | 'deleted';

export type SearchType = 'all' | 'vector' | 'graph' | 'semantic' | 'keyword';

export interface MemoryNode {
  id: string;
  type: MemoryType;
  title: string;
  content: string;
  summary: string;
  source: MemorySource;
  sourceId: string;
  tags: string[];
  concepts: string[];
  confidence: number;
  importance: number;
  accessCount: number;
  agentId: string;
  agentAccess: string[];
  projectId: string;
  teamId: string;
  userId: string;
  vectorEmbedding: number[];
  createdAt: number;
  updatedAt: number;
  lastReferencedAt: number;
  metadata: Record<string, unknown>;
}

export interface MemoryRelation {
  id: string;
  sourceId: string;
  targetId: string;
  relationType: RelationType;
  strength: number;
  autoGenerated: boolean;
  createdAt: number;
}

export interface MemoryExtraction {
  id: string;
  sourceType: string;
  sourceContent: string;
  sourceId: string;
  extractedType: ExtractedType;
  extractedContent: string;
  confidence: number;
  status: ExtractionStatus;
  agentId: string;
  createdAt: number;
}

export interface MemoryTimelineEvent {
  id: string;
  memoryId: string;
  eventType: TimelineEventType;
  agentId: string;
  description: string;
  metadata: Record<string, unknown>;
  createdAt: number;
}

export interface MemorySearchResult {
  memoryId: string;
  score: number;
  searchType: SearchType;
  snippet: string;
}

export type GraphNodeType =
  | 'memory'
  | 'person'
  | 'company'
  | 'project'
  | 'task'
  | 'document'
  | 'concept'
  | 'decision';

export interface GraphNode {
  id: string;
  label: string;
  type: GraphNodeType;
  memoryId?: string;
  properties: Record<string, string>;
  color: string;
  size: number;
  x?: number;
  y?: number;
  vx?: number;
  vy?: number;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  label: string;
  weight: number;
  color: string;
}

// ─── Store Interface ───

interface MemoryState {
  // State
  memories: MemoryNode[];
  memoryRelations: MemoryRelation[];
  memoryExtractions: MemoryExtraction[];
  memoryTimeline: MemoryTimelineEvent[];
  graphNodes: GraphNode[];
  graphEdges: GraphEdge[];
  memorySearchResults: MemorySearchResult[];
  memorySearchQuery: string;
  memorySearchType: SearchType;
  selectedMemoryId: string | null;
  memoryGraphLayout: 'force' | 'radial' | 'hierarchical';

  // Actions — Memory CRUD
  addMemory: (memory: MemoryNode) => void;
  updateMemory: (id: string, updates: Partial<MemoryNode>) => void;
  deleteMemory: (id: string) => void;
  referenceMemory: (id: string) => void;

  // Actions — Relations
  addMemoryRelation: (relation: MemoryRelation) => void;
  removeMemoryRelation: (id: string) => void;

  // Actions — Extractions
  addExtraction: (extraction: MemoryExtraction) => void;
  confirmExtraction: (id: string) => void;
  rejectExtraction: (id: string) => void;

  // Actions — Timeline
  addTimelineEvent: (event: MemoryTimelineEvent) => void;

  // Actions — Search
  searchMemories: (query: string) => void;

  // Actions — Getters
  getMemoryById: (id: string) => MemoryNode | undefined;
  getMemoriesByType: (type: MemoryType) => MemoryNode[];
  getMemoriesByAgent: (agentId: string) => MemoryNode[];
  getRelatedMemories: (memoryId: string) => MemoryRelation[];

  // Actions — Graph
  rebuildGraph: () => void;

  // Actions — Setters
  setMemorySearchQuery: (query: string) => void;
  setMemorySearchType: (type: SearchType) => void;
  setSelectedMemoryId: (id: string | null) => void;
  setMemoryGraphLayout: (layout: 'force' | 'radial' | 'hierarchical') => void;
}

// ─── Color palette for graph nodes ───

const GRAPH_COLORS: Record<GraphNodeType, string> = {
  memory: '#2E86AB',
  person: '#E63946',
  company: '#FFB627',
  project: '#7B2CBF',
  task: '#E8751A',
  document: '#1B998B',
  concept: '#FF8C42',
  decision: '#D62828',
};

const MEMORY_TYPE_COLORS: Record<MemoryType, string> = {
  'long-term': '#2E86AB',
  'short-term': '#5BC0EB',
  episodic: '#E63946',
  semantic: '#7B2CBF',
  context: '#FFB627',
  project: '#E8751A',
  user: '#1B998B',
  team: '#FF8C42',
  conversation: '#D62828',
};

// ─── Seed Data ───

const now = Date.now();
const HOUR = 3600000;
const DAY = 86400000;

const SEED_MEMORIES: MemoryNode[] = [
  {
    id: 'mem-001',
    type: 'long-term',
    title: 'Hermes Configuration Architecture',
    content: 'Hermes config: ~/.hermes/config.yaml (secrets in .env). Supports 20+ LLM providers, model-agnostic architecture. All routing goes through OpenClaw gateway. No direct agent-to-agent communication allowed. The config supports hot-reload without service restart.',
    summary: 'Hermes configuration architecture with multi-provider LLM support and OpenClaw routing',
    source: 'file',
    sourceId: 'file-hermes-config',
    tags: ['config', 'setup', 'architecture', 'hermes'],
    concepts: ['configuration management', 'LLM providers', 'agent routing'],
    confidence: 0.95,
    importance: 0.9,
    accessCount: 34,
    agentId: 'hermes',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 2 * HOUR,
    updatedAt: now - 30 * 60000,
    lastReferencedAt: now - 10 * 60000,
    metadata: { filePath: '~/.hermes/config.yaml', version: '3.2' },
  },
  {
    id: 'mem-002',
    type: 'project',
    title: 'Agent OS v2.0 Launch Plan',
    content: 'Ship Agent OS v2.0 to production this month. Key milestones: cross-agent memory sharing protocol, autonomous task delegation pipeline, and vault expansion to 15K+ entries. Currently at 72% completion. Beta testing showed 40% improvement in agent coordination latency.',
    summary: 'Agent OS v2.0 production launch plan with 72% completion and key milestones',
    source: 'meeting',
    sourceId: 'meeting-2024-q1-launch',
    tags: ['launch', 'v2.0', 'milestone', 'production'],
    concepts: ['product launch', 'milestone tracking', 'agent coordination'],
    confidence: 0.92,
    importance: 0.95,
    accessCount: 67,
    agentId: 'claude',
    agentAccess: ['claude', 'openclaw', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 1 * DAY,
    updatedAt: now - 4 * HOUR,
    lastReferencedAt: now - 2 * HOUR,
    metadata: { meetingDate: '2024-12-15', attendees: ['claude', 'openclaw', 'hermes'] },
  },
  {
    id: 'mem-003',
    type: 'episodic',
    title: 'MCP Integration Breakthrough',
    content: 'Completed Hermes MCP integration — all stdio transports verified. Routed through OpenClaw, no conflicts. The stack is compounding beautifully. Key insight: MCP stdio transport is more reliable than HTTP transport for local development. Switched all local MCP servers to stdio.',
    summary: 'Successful MCP integration with stdio transport through OpenClaw',
    source: 'chat',
    sourceId: 'chat-2024-12-14-001',
    tags: ['mcp', 'integration', 'breakthrough', 'stdio'],
    concepts: ['MCP protocol', 'transport layer', 'integration patterns'],
    confidence: 0.98,
    importance: 0.85,
    accessCount: 23,
    agentId: 'hermes',
    agentAccess: ['claude', 'openclaw', 'hermes'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 2 * DAY,
    updatedAt: now - 2 * DAY,
    lastReferencedAt: now - 6 * HOUR,
    metadata: { transportType: 'stdio', conflictResolution: 'openclaw-routing' },
  },
  {
    id: 'mem-004',
    type: 'semantic',
    title: 'Compound Knowledge Effect',
    content: 'The difference between generic AI and personalised AI is the Memory layer. Without it, agents give generic answers. With it, they give advice as if they\'ve worked at your company for two years. This compound effect accelerates with each day of recording. Day one is good. Day thirty is wild. The vault crossed 12,000 entries and agents are giving noticeably better advice.',
    summary: 'Memory layer creates compound knowledge effect — personalized AI improves exponentially',
    source: 'chat',
    sourceId: 'chat-2024-12-13-insight',
    tags: ['insight', 'compound', 'memory', 'personalization'],
    concepts: ['compound effect', 'personalization', 'knowledge accumulation', 'AI improvement'],
    confidence: 0.88,
    importance: 0.95,
    accessCount: 45,
    agentId: 'vault',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 3 * DAY,
    updatedAt: now - 1 * DAY,
    lastReferencedAt: now - 5 * HOUR,
    metadata: { vaultSize: 12000, compoundDays: 30 },
  },
  {
    id: 'mem-005',
    type: 'user',
    title: 'User Work Preferences',
    content: 'Prefers async communication over real-time meetings. Works best in deep focus blocks of 2-3 hours. Reviews code in the morning, writes in the afternoon. Uses Obsidian for personal knowledge management. Values brevity in agent responses — prefers bullet points over paragraphs. Hates unnecessary ceremony in standups.',
    summary: 'User preferences for async work, focus blocks, and concise communication',
    source: 'chat',
    sourceId: 'chat-preferences-001',
    tags: ['preferences', 'work-style', 'communication'],
    concepts: ['work preferences', 'communication style', 'productivity patterns'],
    confidence: 0.91,
    importance: 0.8,
    accessCount: 89,
    agentId: 'vault',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: '',
    teamId: '',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 7 * DAY,
    updatedAt: now - 2 * DAY,
    lastReferencedAt: now - 1 * HOUR,
    metadata: { preferenceCategory: 'work-style', confidenceTrend: 'increasing' },
  },
  {
    id: 'mem-006',
    type: 'short-term',
    title: 'Current Sprint Tasks',
    content: 'Active sprint: Deploy Hermes v3.2 to production (in progress), Implement cross-agent memory sharing (todo), Optimize vault query latency (done), Research competitor AI stacks (in progress). Sprint ends Friday. Priority is getting Hermes v3.2 stable before the weekend.',
    summary: 'Current sprint tasks with Hermes v3.2 deployment as priority',
    source: 'chat',
    sourceId: 'chat-sprint-2024-12',
    tags: ['sprint', 'tasks', 'hermes', 'deployment'],
    concepts: ['sprint management', 'task prioritization', 'deployment pipeline'],
    confidence: 0.85,
    importance: 0.75,
    accessCount: 56,
    agentId: 'openclaw',
    agentAccess: ['claude', 'openclaw', 'hermes'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 5 * HOUR,
    updatedAt: now - 1 * HOUR,
    lastReferencedAt: now - 15 * 60000,
    metadata: { sprintEnd: '2024-12-20', sprintNumber: 47 },
  },
  {
    id: 'mem-007',
    type: 'context',
    title: 'OpenClaw Session Management Refactor',
    content: 'OpenClaw session management refactored for horizontal scaling. Now handles 3x concurrent agent sessions without degradation. Key change: session state is now stored in shared memory instead of per-process. This enables zero-downtime deployments and better load balancing across instances.',
    summary: 'OpenClaw session management refactored for 3x horizontal scaling',
    source: 'chat',
    sourceId: 'chat-refactor-001',
    tags: ['refactor', 'scaling', 'openclaw', 'sessions'],
    concepts: ['horizontal scaling', 'session management', 'load balancing'],
    confidence: 0.93,
    importance: 0.82,
    accessCount: 18,
    agentId: 'openclaw',
    agentAccess: ['claude', 'openclaw', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 1 * DAY,
    updatedAt: now - 1 * DAY,
    lastReferencedAt: now - 8 * HOUR,
    metadata: { scalingFactor: '3x', sessionStore: 'shared-memory' },
  },
  {
    id: 'mem-008',
    type: 'team',
    title: 'Core Team Communication Protocol',
    content: 'All agent routing must go through OpenClaw. No direct agent-to-agent communication. Broadcast messages require at least 2 acknowledgments. Critical messages use exponential backoff retry with 3 attempts. Each agent maintains its own context window but shares via the Memory layer.',
    summary: 'Team communication protocol via OpenClaw with broadcast and retry rules',
    source: 'document',
    sourceId: 'doc-comm-protocol',
    tags: ['protocol', 'communication', 'routing', 'rules'],
    concepts: ['communication protocol', 'message routing', 'reliability patterns'],
    confidence: 0.97,
    importance: 0.88,
    accessCount: 72,
    agentId: 'openclaw',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 10 * DAY,
    updatedAt: now - 3 * DAY,
    lastReferencedAt: now - 3 * HOUR,
    metadata: { protocolVersion: '2.1', backwardCompatible: true },
  },
  {
    id: 'mem-009',
    type: 'conversation',
    title: 'Claude Vision Pipeline Upgrade Discussion',
    content: 'Claude vision pipeline upgraded to support multi-frame analysis. The Cognition layer can now reason over video streams. This is a massive unlock for research delegation — Claude can watch a demo video and extract the key features, then delegate research tasks to Hermes. Performance cost: ~2x token usage for video frames.',
    summary: 'Claude vision pipeline now supports multi-frame video analysis for research delegation',
    source: 'chat',
    sourceId: 'chat-vision-upgrade',
    tags: ['vision', 'upgrade', 'video', 'cognition'],
    concepts: ['vision pipeline', 'video analysis', 'research delegation', 'token optimization'],
    confidence: 0.90,
    importance: 0.87,
    accessCount: 31,
    agentId: 'claude',
    agentAccess: ['claude', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 4 * DAY,
    updatedAt: now - 4 * DAY,
    lastReferencedAt: now - 12 * HOUR,
    metadata: { tokenMultiplier: 2, frameSupport: true },
  },
  {
    id: 'mem-010',
    type: 'long-term',
    title: 'Vault Structure and Organization',
    content: 'Vault structure: Goals/ tracked weekly, Journal/ daily entries, Memory/ auto-saved from every chat. All agents read from vault for context. The vault uses a graph-based index for fast retrieval. Entries are tagged with agent IDs, timestamps, and relevance scores. Auto-pruning runs weekly for entries older than 90 days with accessCount < 2.',
    summary: 'Vault organized into Goals, Journal, Memory with graph index and auto-pruning',
    source: 'file',
    sourceId: 'file-vault-structure',
    tags: ['vault', 'structure', 'organization', 'indexing'],
    concepts: ['knowledge management', 'graph indexing', 'auto-pruning', 'vault structure'],
    confidence: 0.96,
    importance: 0.92,
    accessCount: 103,
    agentId: 'vault',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 14 * DAY,
    updatedAt: now - 2 * DAY,
    lastReferencedAt: now - 45 * 60000,
    metadata: { pruningThreshold: 90, minAccessCount: 2, indexType: 'graph' },
  },
  {
    id: 'mem-011',
    type: 'semantic',
    title: 'OMI Recording and Auto-Export',
    content: 'OMI records screen + mic all day → exports to Obsidian vault. This is what makes the system compound. Every day it knows more about you, your business, and your priorities. The auto-export runs every 30 minutes and processes the recordings into structured notes with tags, timestamps, and extracted action items.',
    summary: 'OMI continuous recording with 30-minute auto-export to Obsidian vault',
    source: 'chat',
    sourceId: 'chat-omi-setup',
    tags: ['omi', 'recording', 'auto-export', 'obsidian'],
    concepts: ['continuous recording', 'auto-export', 'structured notes', 'action items'],
    confidence: 0.94,
    importance: 0.83,
    accessCount: 28,
    agentId: 'vault',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 5 * DAY,
    updatedAt: now - 5 * DAY,
    lastReferencedAt: now - 1 * DAY,
    metadata: { exportInterval: '30min', outputFormat: 'structured-notes' },
  },
  {
    id: 'mem-012',
    type: 'project',
    title: 'Cross-Agent Memory Sharing Protocol',
    content: 'Design for cross-agent memory sharing: Each agent publishes memory entries to the shared vault. Access control via agentAccess array. Confidence scoring determines which memories are shared broadly vs. kept internal. Versioning prevents conflicts when multiple agents update the same memory. Currently at 30% implementation — the access control layer is done, working on conflict resolution.',
    summary: 'Cross-agent memory sharing protocol with access control and conflict resolution at 30%',
    source: 'document',
    sourceId: 'doc-memory-sharing',
    tags: ['sharing', 'protocol', 'access-control', 'conflict-resolution'],
    concepts: ['memory sharing', 'access control', 'conflict resolution', 'versioning'],
    confidence: 0.78,
    importance: 0.9,
    accessCount: 41,
    agentId: 'openclaw',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 6 * DAY,
    updatedAt: now - 12 * HOUR,
    lastReferencedAt: now - 4 * HOUR,
    metadata: { implementationProgress: '30%', completedComponents: ['access-control'] },
  },
  {
    id: 'mem-013',
    type: 'episodic',
    title: 'Browser Automation Performance Issue',
    content: 'Browser pool at capacity during competitor analysis. Hermes was running 8 concurrent browser sessions which exceeded the Browserbase limit of 5. Resolved by implementing a queue with priority scheduling. High-priority research tasks get immediate browser access, low-priority tasks wait for off-peak hours. This reduced browser timeout errors by 90%.',
    summary: 'Browser pool capacity issue resolved with priority queue scheduling',
    source: 'chat',
    sourceId: 'chat-browser-issue',
    tags: ['browser', 'performance', 'queue', 'browserbase'],
    concepts: ['resource management', 'priority queue', 'browser automation', 'error reduction'],
    confidence: 0.87,
    importance: 0.72,
    accessCount: 15,
    agentId: 'hermes',
    agentAccess: ['claude', 'hermes'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 3 * DAY,
    updatedAt: now - 3 * DAY,
    lastReferencedAt: now - 1 * DAY,
    metadata: { maxConcurrentSessions: 5, previousLimit: 8, errorReduction: '90%' },
  },
  {
    id: 'mem-014',
    type: 'user',
    title: 'User Technical Stack Preferences',
    content: 'Prefers TypeScript for all new projects. Uses Next.js with App Router for web apps. Prisma for database ORM. Zustand for state management. Tailwind CSS for styling. Avoids Redux and class-based components. Values type safety and strict TypeScript config. Uses pnpm over npm for workspace management.',
    summary: 'User tech stack preferences: TypeScript, Next.js, Prisma, Zustand, Tailwind',
    source: 'chat',
    sourceId: 'chat-tech-prefs',
    tags: ['preferences', 'tech-stack', 'typescript', 'nextjs'],
    concepts: ['technology preferences', 'TypeScript', 'React ecosystem', 'tool selection'],
    confidence: 0.93,
    importance: 0.78,
    accessCount: 62,
    agentId: 'vault',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: '',
    teamId: '',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 8 * DAY,
    updatedAt: now - 3 * DAY,
    lastReferencedAt: now - 6 * HOUR,
    metadata: { preferenceCategory: 'tech-stack', lastVerified: now - 3 * DAY },
  },
  {
    id: 'mem-015',
    type: 'context',
    title: 'Claude MCMC Mode Requirements',
    content: 'Claude MCMC mode requires 64K+ token context window. Vision pipeline active. Full code execution capabilities enabled. MCMC sampling improves reasoning quality by 35% on multi-step problems. Trade-off: 2x latency and 3x token cost. Use only for complex reasoning tasks — simple queries should use standard mode.',
    summary: 'Claude MCMC mode needs 64K context window, improves reasoning by 35% at higher cost',
    source: 'file',
    sourceId: 'file-claude-mcmc',
    tags: ['claude', 'mcmc', 'reasoning', 'performance'],
    concepts: ['MCMC sampling', 'reasoning optimization', 'token management', 'mode selection'],
    confidence: 0.91,
    importance: 0.76,
    accessCount: 22,
    agentId: 'claude',
    agentAccess: ['claude', 'openclaw'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 2 * DAY,
    updatedAt: now - 2 * DAY,
    lastReferencedAt: now - 10 * HOUR,
    metadata: { minContextWindow: '64K', reasoningImprovement: '35%', latencyMultiplier: 2, tokenCostMultiplier: 3 },
  },
  {
    id: 'mem-016',
    type: 'team',
    title: 'Agent Capability Matrix',
    content: 'Claude: reasoning, vision, code execution, MCP. OpenClaw: routing, governance, coordination, security. Hermes: research, execution, browser automation, skills. Vault: memory, personalization, OMI recording, compound knowledge. Cross-training in progress — Hermes learning basic governance, Vault learning basic research.',
    summary: 'Agent capability matrix with specialization areas and cross-training progress',
    source: 'document',
    sourceId: 'doc-agent-matrix',
    tags: ['agents', 'capabilities', 'matrix', 'specialization'],
    concepts: ['agent capabilities', 'specialization', 'cross-training', 'role assignment'],
    confidence: 0.94,
    importance: 0.85,
    accessCount: 38,
    agentId: 'openclaw',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 12 * DAY,
    updatedAt: now - 5 * DAY,
    lastReferencedAt: now - 7 * HOUR,
    metadata: { crossTrainingProgress: '15%', lastUpdated: now - 5 * DAY },
  },
  {
    id: 'mem-017',
    type: 'conversation',
    title: 'Competitor Analysis Research Session',
    content: 'Research session on competitor AI stacks: AutoGPT focuses on autonomous loops but lacks memory persistence. CrewAI has good multi-agent coordination but no compound knowledge. LangGraph excels at workflow orchestration but weak on personalization. Our key differentiator is the Memory layer — no other system compounds knowledge over time the way we do.',
    summary: 'Competitor analysis showing our memory layer as key differentiator',
    source: 'chat',
    sourceId: 'chat-competitor-analysis',
    tags: ['competitor', 'analysis', 'differentiator', 'market'],
    concepts: ['competitive analysis', 'market positioning', 'differentiation strategy', 'AI agent landscape'],
    confidence: 0.82,
    importance: 0.88,
    accessCount: 27,
    agentId: 'hermes',
    agentAccess: ['claude', 'openclaw', 'hermes', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 1 * DAY,
    updatedAt: now - 1 * DAY,
    lastReferencedAt: now - 5 * HOUR,
    metadata: { competitors: ['AutoGPT', 'CrewAI', 'LangGraph'], researchDepth: 'deep' },
  },
  {
    id: 'mem-018',
    type: 'episodic',
    title: 'Production Incident: Token Budget Overflow',
    content: 'Production incident at 3:47 AM: Claude consumed 847K tokens in a single reasoning chain, exceeding the daily budget of $50. Root cause: infinite loop in MCMC sampling when presented with an ambiguous query. Fix: added circuit breaker that caps reasoning chains at 200K tokens and 5 minutes. Also added budget alerting at 80% threshold.',
    summary: 'Token budget overflow incident resolved with circuit breaker and alerting',
    source: 'email',
    sourceId: 'email-incident-2024-12',
    tags: ['incident', 'token-budget', 'circuit-breaker', 'production'],
    concepts: ['incident response', 'circuit breaker', 'budget management', 'error handling'],
    confidence: 0.99,
    importance: 0.92,
    accessCount: 33,
    agentId: 'claude',
    agentAccess: ['claude', 'openclaw', 'vault'],
    projectId: 'proj-agent-os',
    teamId: 'team-core',
    userId: 'user-1',
    vectorEmbedding: [],
    createdAt: now - 4 * DAY,
    updatedAt: now - 4 * DAY,
    lastReferencedAt: now - 2 * DAY,
    metadata: { incidentSeverity: 'high', tokenOverflow: '847K', fixDeployed: true },
  },
];

const SEED_RELATIONS: MemoryRelation[] = [
  {
    id: 'rel-001',
    sourceId: 'mem-001',
    targetId: 'mem-008',
    relationType: 'references',
    strength: 0.9,
    autoGenerated: true,
    createdAt: now - 2 * HOUR,
  },
  {
    id: 'rel-002',
    sourceId: 'mem-002',
    targetId: 'mem-012',
    relationType: 'depends_on',
    strength: 0.85,
    autoGenerated: true,
    createdAt: now - 1 * DAY,
  },
  {
    id: 'rel-003',
    sourceId: 'mem-004',
    targetId: 'mem-010',
    relationType: 'supports',
    strength: 0.92,
    autoGenerated: true,
    createdAt: now - 3 * DAY,
  },
  {
    id: 'rel-004',
    sourceId: 'mem-009',
    targetId: 'mem-015',
    relationType: 'relates_to',
    strength: 0.75,
    autoGenerated: true,
    createdAt: now - 4 * DAY,
  },
  {
    id: 'rel-005',
    sourceId: 'mem-011',
    targetId: 'mem-004',
    relationType: 'causes',
    strength: 0.88,
    autoGenerated: true,
    createdAt: now - 5 * DAY,
  },
  {
    id: 'rel-006',
    sourceId: 'mem-003',
    targetId: 'mem-001',
    relationType: 'derived_from',
    strength: 0.8,
    autoGenerated: true,
    createdAt: now - 2 * DAY,
  },
  {
    id: 'rel-007',
    sourceId: 'mem-006',
    targetId: 'mem-002',
    relationType: 'part_of',
    strength: 0.95,
    autoGenerated: false,
    createdAt: now - 5 * HOUR,
  },
  {
    id: 'rel-008',
    sourceId: 'mem-018',
    targetId: 'mem-015',
    relationType: 'causes',
    strength: 0.9,
    autoGenerated: true,
    createdAt: now - 4 * DAY,
  },
  {
    id: 'rel-009',
    sourceId: 'mem-016',
    targetId: 'mem-008',
    relationType: 'references',
    strength: 0.7,
    autoGenerated: true,
    createdAt: now - 12 * DAY,
  },
  {
    id: 'rel-010',
    sourceId: 'mem-013',
    targetId: 'mem-001',
    relationType: 'relates_to',
    strength: 0.65,
    autoGenerated: true,
    createdAt: now - 3 * DAY,
  },
  {
    id: 'rel-011',
    sourceId: 'mem-017',
    targetId: 'mem-004',
    relationType: 'supports',
    strength: 0.82,
    autoGenerated: true,
    createdAt: now - 1 * DAY,
  },
  {
    id: 'rel-012',
    sourceId: 'mem-007',
    targetId: 'mem-008',
    relationType: 'derived_from',
    strength: 0.78,
    autoGenerated: false,
    createdAt: now - 1 * DAY,
  },
];

const SEED_EXTRACTIONS: MemoryExtraction[] = [
  {
    id: 'ext-001',
    sourceType: 'chat',
    sourceContent: 'Hermes config: ~/.hermes/config.yaml (secrets in .env). Supports 20+ LLM providers, model-agnostic architecture.',
    sourceId: 'chat-2024-12-14-001',
    extractedType: 'fact',
    extractedContent: 'Hermes configuration file is located at ~/.hermes/config.yaml with secrets stored separately in .env',
    confidence: 0.95,
    status: 'confirmed',
    agentId: 'vault',
    createdAt: now - 2 * HOUR,
  },
  {
    id: 'ext-002',
    sourceType: 'chat',
    sourceContent: 'Ship Agent OS v2.0 to production this month. Key milestones: cross-agent memory sharing protocol, autonomous task delegation pipeline.',
    sourceId: 'chat-2024-12-15-001',
    extractedType: 'goal',
    extractedContent: 'Ship Agent OS v2.0 to production this month',
    confidence: 0.92,
    status: 'confirmed',
    agentId: 'claude',
    createdAt: now - 1 * DAY,
  },
  {
    id: 'ext-003',
    sourceType: 'chat',
    sourceContent: 'Prefers async communication over real-time meetings. Works best in deep focus blocks of 2-3 hours.',
    sourceId: 'chat-preferences-001',
    extractedType: 'preference',
    extractedContent: 'User prefers async communication and deep focus blocks of 2-3 hours',
    confidence: 0.91,
    status: 'confirmed',
    agentId: 'vault',
    createdAt: now - 7 * DAY,
  },
  {
    id: 'ext-004',
    sourceType: 'chat',
    sourceContent: 'Production incident at 3:47 AM: Claude consumed 847K tokens in a single reasoning chain, exceeding the daily budget of $50.',
    sourceId: 'email-incident-2024-12',
    extractedType: 'requirement',
    extractedContent: 'Add circuit breaker capping reasoning chains at 200K tokens and 5 minutes maximum',
    confidence: 0.88,
    status: 'confirmed',
    agentId: 'claude',
    createdAt: now - 4 * DAY,
  },
  {
    id: 'ext-005',
    sourceType: 'chat',
    sourceContent: 'OpenClaw session management refactored for horizontal scaling. Now handles 3x concurrent agent sessions without degradation.',
    sourceId: 'chat-refactor-001',
    extractedType: 'decision',
    extractedContent: 'Session state moved to shared memory for horizontal scaling and zero-downtime deployments',
    confidence: 0.93,
    status: 'confirmed',
    agentId: 'openclaw',
    createdAt: now - 1 * DAY,
  },
  {
    id: 'ext-006',
    sourceType: 'chat',
    sourceContent: 'Browser pool at capacity during competitor analysis. Hermes was running 8 concurrent browser sessions which exceeded the Browserbase limit of 5.',
    sourceId: 'chat-browser-issue',
    extractedType: 'task',
    extractedContent: 'Implement priority queue for browser session management to prevent capacity overflow',
    confidence: 0.85,
    status: 'confirmed',
    agentId: 'hermes',
    createdAt: now - 3 * DAY,
  },
  {
    id: 'ext-007',
    sourceType: 'chat',
    sourceContent: 'Our key differentiator is the Memory layer — no other system compounds knowledge over time the way we do.',
    sourceId: 'chat-competitor-analysis',
    extractedType: 'fact',
    extractedContent: 'Memory layer with compound knowledge effect is the key differentiator from competitors',
    confidence: 0.82,
    status: 'pending',
    agentId: 'hermes',
    createdAt: now - 1 * DAY,
  },
  {
    id: 'ext-008',
    sourceType: 'email',
    sourceContent: 'Contact Sarah from Browserbase about enterprise pricing for higher concurrent session limits.',
    sourceId: 'email-browserbase-pricing',
    extractedType: 'contact',
    extractedContent: 'Sarah at Browserbase — enterprise pricing contact for higher concurrent session limits',
    confidence: 0.79,
    status: 'pending',
    agentId: 'hermes',
    createdAt: now - 2 * DAY,
  },
  {
    id: 'ext-009',
    sourceType: 'chat',
    sourceContent: 'Prefers TypeScript for all new projects. Uses Next.js with App Router for web apps. Prisma for database ORM.',
    sourceId: 'chat-tech-prefs',
    extractedType: 'preference',
    extractedContent: 'User tech stack: TypeScript, Next.js App Router, Prisma ORM, Zustand, Tailwind CSS',
    confidence: 0.93,
    status: 'confirmed',
    agentId: 'vault',
    createdAt: now - 8 * DAY,
  },
  {
    id: 'ext-010',
    sourceType: 'meeting',
    sourceContent: 'Agentic Inc. is the company behind Agent OS. Focused on building compound intelligence systems.',
    sourceId: 'meeting-2024-q1-launch',
    extractedType: 'company',
    extractedContent: 'Agentic Inc. — building compound intelligence systems, company behind Agent OS',
    confidence: 0.9,
    status: 'confirmed',
    agentId: 'claude',
    createdAt: now - 1 * DAY,
  },
];

const SEED_TIMELINE: MemoryTimelineEvent[] = [
  {
    id: 'tl-001',
    memoryId: 'mem-001',
    eventType: 'created',
    agentId: 'hermes',
    description: 'Hermes configuration architecture documented',
    metadata: { source: 'file' },
    createdAt: now - 2 * HOUR,
  },
  {
    id: 'tl-002',
    memoryId: 'mem-002',
    eventType: 'created',
    agentId: 'claude',
    description: 'Agent OS v2.0 launch plan created from meeting notes',
    metadata: { source: 'meeting' },
    createdAt: now - 1 * DAY,
  },
  {
    id: 'tl-003',
    memoryId: 'mem-002',
    eventType: 'updated',
    agentId: 'claude',
    description: 'Launch plan progress updated to 72%',
    metadata: { previousProgress: '65%' },
    createdAt: now - 4 * HOUR,
  },
  {
    id: 'tl-004',
    memoryId: 'mem-003',
    eventType: 'created',
    agentId: 'hermes',
    description: 'MCP integration breakthrough recorded',
    metadata: { source: 'chat' },
    createdAt: now - 2 * DAY,
  },
  {
    id: 'tl-005',
    memoryId: 'mem-004',
    eventType: 'referenced',
    agentId: 'claude',
    description: 'Compound knowledge effect referenced during competitor analysis',
    metadata: { context: 'competitive-research' },
    createdAt: now - 5 * HOUR,
  },
  {
    id: 'tl-006',
    memoryId: 'mem-005',
    eventType: 'referenced',
    agentId: 'claude',
    description: 'User work preferences loaded for personalized response',
    metadata: { context: 'chat-response' },
    createdAt: now - 1 * HOUR,
  },
  {
    id: 'tl-007',
    memoryId: 'mem-018',
    eventType: 'created',
    agentId: 'claude',
    description: 'Production incident recorded — token budget overflow',
    metadata: { severity: 'high' },
    createdAt: now - 4 * DAY,
  },
  {
    id: 'tl-008',
    memoryId: 'mem-018',
    eventType: 'updated',
    agentId: 'openclaw',
    description: 'Circuit breaker fix applied and verified',
    metadata: { fixDeployed: true },
    createdAt: now - 4 * DAY + 2 * HOUR,
  },
  {
    id: 'tl-009',
    memoryId: 'mem-010',
    eventType: 'referenced',
    agentId: 'vault',
    description: 'Vault structure referenced during cross-agent sharing design',
    metadata: { context: 'sharing-protocol' },
    createdAt: now - 45 * 60000,
  },
  {
    id: 'tl-010',
    memoryId: 'mem-006',
    eventType: 'updated',
    agentId: 'openclaw',
    description: 'Sprint task status updated — Hermes v3.2 in progress',
    metadata: { previousStatus: 'todo' },
    createdAt: now - 1 * HOUR,
  },
  {
    id: 'tl-011',
    memoryId: 'mem-011',
    eventType: 'extracted',
    agentId: 'vault',
    description: 'Extracted auto-export configuration details from OMI recording discussion',
    metadata: { extractionId: 'ext-007' },
    createdAt: now - 5 * DAY,
  },
  {
    id: 'tl-012',
    memoryId: 'mem-017',
    eventType: 'created',
    agentId: 'hermes',
    description: 'Competitor analysis research session documented',
    metadata: { source: 'chat', competitors: 3 },
    createdAt: now - 1 * DAY,
  },
  {
    id: 'tl-013',
    memoryId: 'mem-012',
    eventType: 'shared',
    agentId: 'openclaw',
    description: 'Memory sharing protocol design shared with all agents',
    metadata: { sharedWith: ['claude', 'hermes', 'vault'] },
    createdAt: now - 12 * HOUR,
  },
  {
    id: 'tl-014',
    memoryId: 'mem-009',
    eventType: 'created',
    agentId: 'claude',
    description: 'Vision pipeline upgrade discussion captured',
    metadata: { source: 'chat' },
    createdAt: now - 4 * DAY,
  },
  {
    id: 'tl-015',
    memoryId: 'mem-007',
    eventType: 'extracted',
    agentId: 'openclaw',
    description: 'Session management refactor decision extracted',
    metadata: { extractionId: 'ext-005' },
    createdAt: now - 1 * DAY,
  },
];

// ─── Search Engine ───

function performSearch(
  memories: MemoryNode[],
  query: string,
  searchType: SearchType,
): MemorySearchResult[] {
  if (!query.trim()) return [];

  const lowerQuery = query.toLowerCase().trim();
  const queryWords = lowerQuery.split(/\s+/).filter((w) => w.length > 1);
  const results: MemorySearchResult[] = [];

  for (const mem of memories) {
    let score = 0;
    const lowerTitle = mem.title.toLowerCase();
    const lowerContent = mem.content.toLowerCase();
    const lowerTags = mem.tags.map((t) => t.toLowerCase());
    const lowerConcepts = mem.concepts.map((c) => c.toLowerCase());
    const lowerSummary = mem.summary.toLowerCase();

    // ── Exact title match (highest score) ──
    if (lowerTitle === lowerQuery) {
      score += 100;
    } else if (lowerTitle.includes(lowerQuery)) {
      score += 70;
    } else {
      // Partial title word matches
      for (const word of queryWords) {
        if (lowerTitle.includes(word)) {
          score += 20;
        }
      }
    }

    // ── Exact tag match ──
    for (const tag of lowerTags) {
      if (tag === lowerQuery) {
        score += 60;
      } else if (queryWords.some((w) => tag.includes(w))) {
        score += 25;
      }
    }

    // ── Exact concept match ──
    for (const concept of lowerConcepts) {
      if (concept === lowerQuery) {
        score += 50;
      } else if (queryWords.some((w) => concept.includes(w))) {
        score += 20;
      }
    }

    // ── Content / summary partial match ──
    if (lowerContent.includes(lowerQuery)) {
      score += 40;
    } else if (lowerSummary.includes(lowerQuery)) {
      score += 30;
    } else {
      // Word-level content matching
      let contentWordMatches = 0;
      for (const word of queryWords) {
        if (lowerContent.includes(word)) {
          contentWordMatches++;
        }
      }
      score += contentWordMatches * 8;

      let summaryWordMatches = 0;
      for (const word of queryWords) {
        if (lowerSummary.includes(word)) {
          summaryWordMatches++;
        }
      }
      score += summaryWordMatches * 6;
    }

    // ── Boost by importance and confidence ──
    score += mem.importance * 10;
    score += mem.confidence * 5;

    // ── Boost by recency ──
    const ageHours = (now - mem.lastReferencedAt) / HOUR;
    if (ageHours < 1) score += 15;
    else if (ageHours < 6) score += 10;
    else if (ageHours < 24) score += 5;

    // ── Boost by access count (popular memories) ──
    if (mem.accessCount > 50) score += 10;
    else if (mem.accessCount > 20) score += 5;

    if (score > 0) {
      // Generate a snippet from content around the first match
      let snippet = '';
      const idx = lowerContent.indexOf(lowerQuery);
      if (idx >= 0) {
        const start = Math.max(0, idx - 40);
        const end = Math.min(mem.content.length, idx + lowerQuery.length + 60);
        snippet =
          (start > 0 ? '...' : '') +
          mem.content.slice(start, end) +
          (end < mem.content.length ? '...' : '');
      } else {
        // Use first 120 chars of summary as snippet
        snippet = mem.summary.slice(0, 120) + (mem.summary.length > 120 ? '...' : '');
      }

      // Determine effective search type label
      let effectiveSearchType: SearchType = searchType;
      if (searchType === 'all') {
        if (lowerTitle.includes(lowerQuery) || lowerTags.some((t) => t.includes(lowerQuery))) {
          effectiveSearchType = 'keyword';
        } else if (lowerConcepts.some((c) => c.includes(lowerQuery))) {
          effectiveSearchType = 'semantic';
        } else {
          effectiveSearchType = 'keyword';
        }
      }

      results.push({
        memoryId: mem.id,
        score: Math.round(score * 100) / 100,
        searchType: effectiveSearchType,
        snippet,
      });
    }
  }

  // Sort by score descending
  results.sort((a, b) => b.score - a.score);

  return results;
}

// ─── Graph Builder ───

function buildGraphFromMemories(
  memories: MemoryNode[],
  relations: MemoryRelation[],
): { nodes: GraphNode[]; edges: GraphEdge[] } {
  const nodes: GraphNode[] = [];
  const edges: GraphEdge[] = [];

  // Create memory nodes
  for (const mem of memories) {
    nodes.push({
      id: `node-${mem.id}`,
      label: mem.title.length > 30 ? mem.title.slice(0, 30) + '...' : mem.title,
      type: 'memory',
      memoryId: mem.id,
      properties: {
        memoryType: mem.type,
        source: mem.source,
        agentId: mem.agentId,
        importance: mem.importance.toFixed(2),
      },
      color: MEMORY_TYPE_COLORS[mem.type],
      size: 8 + mem.importance * 12 + Math.min(mem.accessCount / 10, 8),
      x: Math.random() * 600 - 300,
      y: Math.random() * 600 - 300,
    });
  }

  // Extract unique agents as person nodes
  const agentIds = [...new Set(memories.map((m) => m.agentId))];
  for (const agentId of agentIds) {
    nodes.push({
      id: `node-agent-${agentId}`,
      label: agentId.charAt(0).toUpperCase() + agentId.slice(1),
      type: 'person',
      properties: { role: 'agent' },
      color: GRAPH_COLORS.person,
      size: 16,
      x: Math.random() * 600 - 300,
      y: Math.random() * 600 - 300,
    });
  }

  // Extract unique concepts as concept nodes
  const allConcepts = [...new Set(memories.flatMap((m) => m.concepts))];
  // Only create concept nodes for concepts that appear in 2+ memories
  const conceptCounts: Record<string, number> = {};
  for (const c of allConcepts) {
    conceptCounts[c] = (conceptCounts[c] || 0) + 1;
  }
  const sharedConcepts = allConcepts.filter((c) => (conceptCounts[c] || 0) >= 2);
  for (const concept of sharedConcepts.slice(0, 15)) {
    // limit to 15 concept nodes
    nodes.push({
      id: `node-concept-${concept.replace(/\s+/g, '-')}`,
      label: concept,
      type: 'concept',
      properties: { count: String(conceptCounts[concept] || 0) },
      color: GRAPH_COLORS.concept,
      size: 6 + (conceptCounts[concept] || 0) * 2,
      x: Math.random() * 600 - 300,
      y: Math.random() * 600 - 300,
    });
  }

  // Extract projects
  const projectIds = [...new Set(memories.filter((m) => m.projectId).map((m) => m.projectId))];
  for (const projId of projectIds) {
    nodes.push({
      id: `node-project-${projId}`,
      label: projId.replace(/proj-/, '').replace(/-/g, ' '),
      type: 'project',
      properties: {},
      color: GRAPH_COLORS.project,
      size: 14,
      x: Math.random() * 600 - 300,
      y: Math.random() * 600 - 300,
    });
  }

  // Create edges from relations
  for (const rel of relations) {
    const sourceNode = `node-${rel.sourceId}`;
    const targetNode = `node-${rel.targetId}`;
    // Only add if both nodes exist
    if (memories.some((m) => m.id === rel.sourceId) && memories.some((m) => m.id === rel.targetId)) {
      const edgeColor = rel.relationType === 'causes'
        ? '#E63946'
        : rel.relationType === 'depends_on'
          ? '#FFB627'
          : rel.relationType === 'contradicts'
            ? '#D62828'
            : rel.relationType === 'supports'
              ? '#1B998B'
              : '#555555';
      edges.push({
        id: rel.id,
        source: sourceNode,
        target: targetNode,
        label: rel.relationType.replace(/_/g, ' '),
        weight: rel.strength,
        color: edgeColor,
      });
    }
  }

  // Create edges from memories to their agents
  for (const mem of memories) {
    edges.push({
      id: `edge-agent-${mem.id}`,
      source: `node-${mem.id}`,
      target: `node-agent-${mem.agentId}`,
      label: 'created by',
      weight: 0.5,
      color: '#888888',
    });
  }

  // Create edges from memories to concepts
  for (const mem of memories) {
    for (const concept of mem.concepts) {
      const conceptNodeId = `node-concept-${concept.replace(/\s+/g, '-')}`;
      if (sharedConcepts.includes(concept)) {
        edges.push({
          id: `edge-concept-${mem.id}-${concept.replace(/\s+/g, '-')}`,
          source: `node-${mem.id}`,
          target: conceptNodeId,
          label: 'about',
          weight: 0.3,
          color: '#AAAAAA',
        });
      }
    }
  }

  // Create edges from memories to projects
  for (const mem of memories) {
    if (mem.projectId) {
      edges.push({
        id: `edge-project-${mem.id}`,
        source: `node-${mem.id}`,
        target: `node-project-${mem.projectId}`,
        label: 'part of',
        weight: 0.6,
        color: '#7B2CBF',
      });
    }
  }

  return { nodes, edges };
}

// ─── Store ───

export const useMemoryStore = create<MemoryState>((set, get) => ({
  // ── State ──
  memories: SEED_MEMORIES,
  memoryRelations: SEED_RELATIONS,
  memoryExtractions: SEED_EXTRACTIONS,
  memoryTimeline: SEED_TIMELINE,
  graphNodes: [],
  graphEdges: [],
  memorySearchResults: [],
  memorySearchQuery: '',
  memorySearchType: 'all',
  selectedMemoryId: null,
  memoryGraphLayout: 'force',

  // ── Memory CRUD ──
  addMemory: (memory) =>
    set((state) => {
      const newMemories = [memory, ...state.memories];
      const { nodes, edges } = buildGraphFromMemories(newMemories, state.memoryRelations);
      return {
        memories: newMemories,
        graphNodes: nodes,
        graphEdges: edges,
      };
    }),

  updateMemory: (id, updates) =>
    set((state) => {
      const newMemories = state.memories.map((m) =>
        m.id === id ? { ...m, ...updates, updatedAt: Date.now() } : m,
      );
      const { nodes, edges } = buildGraphFromMemories(newMemories, state.memoryRelations);
      return {
        memories: newMemories,
        graphNodes: nodes,
        graphEdges: edges,
      };
    }),

  deleteMemory: (id) =>
    set((state) => {
      const newMemories = state.memories.filter((m) => m.id !== id);
      const newRelations = state.memoryRelations.filter(
        (r) => r.sourceId !== id && r.targetId !== id,
      );
      const newExtractions = state.memoryExtractions.filter((e) => e.sourceId !== id);
      const newTimeline = state.memoryTimeline.filter((t) => t.memoryId !== id);
      const { nodes, edges } = buildGraphFromMemories(newMemories, newRelations);
      return {
        memories: newMemories,
        memoryRelations: newRelations,
        memoryExtractions: newExtractions,
        memoryTimeline: newTimeline,
        graphNodes: nodes,
        graphEdges: edges,
        selectedMemoryId: state.selectedMemoryId === id ? null : state.selectedMemoryId,
      };
    }),

  referenceMemory: (id) =>
    set((state) => ({
      memories: state.memories.map((m) =>
        m.id === id
          ? { ...m, accessCount: m.accessCount + 1, lastReferencedAt: Date.now() }
          : m,
      ),
    })),

  // ── Relations ──
  addMemoryRelation: (relation) =>
    set((state) => {
      const newRelations = [...state.memoryRelations, relation];
      const { nodes, edges } = buildGraphFromMemories(state.memories, newRelations);
      return {
        memoryRelations: newRelations,
        graphNodes: nodes,
        graphEdges: edges,
      };
    }),

  removeMemoryRelation: (id) =>
    set((state) => {
      const newRelations = state.memoryRelations.filter((r) => r.id !== id);
      const { nodes, edges } = buildGraphFromMemories(state.memories, newRelations);
      return {
        memoryRelations: newRelations,
        graphNodes: nodes,
        graphEdges: edges,
      };
    }),

  // ── Extractions ──
  addExtraction: (extraction) =>
    set((state) => ({
      memoryExtractions: [extraction, ...state.memoryExtractions],
    })),

  confirmExtraction: (id) =>
    set((state) => ({
      memoryExtractions: state.memoryExtractions.map((e) =>
        e.id === id ? { ...e, status: 'confirmed' as ExtractionStatus } : e,
      ),
    })),

  rejectExtraction: (id) =>
    set((state) => ({
      memoryExtractions: state.memoryExtractions.map((e) =>
        e.id === id ? { ...e, status: 'rejected' as ExtractionStatus } : e,
      ),
    })),

  // ── Timeline ──
  addTimelineEvent: (event) =>
    set((state) => ({
      memoryTimeline: [event, ...state.memoryTimeline].slice(0, 200),
    })),

  // ── Search ──
  searchMemories: (query) => {
    const state = get();
    const results = performSearch(state.memories, query, state.memorySearchType);
    set({ memorySearchResults: results, memorySearchQuery: query });
  },

  // ── Getters ──
  getMemoryById: (id) => {
    return get().memories.find((m) => m.id === id);
  },

  getMemoriesByType: (type) => {
    return get().memories.filter((m) => m.type === type);
  },

  getMemoriesByAgent: (agentId) => {
    return get().memories.filter((m) => m.agentId === agentId);
  },

  getRelatedMemories: (memoryId) => {
    return get().memoryRelations.filter(
      (r) => r.sourceId === memoryId || r.targetId === memoryId,
    );
  },

  // ── Graph ──
  rebuildGraph: () =>
    set((state) => {
      const { nodes, edges } = buildGraphFromMemories(state.memories, state.memoryRelations);
      return { graphNodes: nodes, graphEdges: edges };
    }),

  // ── Setters ──
  setMemorySearchQuery: (query) => set({ memorySearchQuery: query }),

  setMemorySearchType: (type) => set({ memorySearchType: type }),

  setSelectedMemoryId: (id) => set({ selectedMemoryId: id }),

  setMemoryGraphLayout: (layout) => set({ memoryGraphLayout: layout }),
}));

// Initialize the graph on first import
const initialGraph = buildGraphFromMemories(SEED_MEMORIES, SEED_RELATIONS);
useMemoryStore.setState({
  graphNodes: initialGraph.nodes,
  graphEdges: initialGraph.edges,
});
